# Generated by Django 4.2.2 on 2023-06-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=40)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.countries')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.indicators')),
            ],
        ),
    ]
