# Generated by Django 4.2.2 on 2023-06-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'indicators',
            },
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=40)),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='blog.countries')),
                ('indicator', models.ForeignKey(db_column='indicator', on_delete=django.db.models.deletion.CASCADE, to='blog.indicators')),
            ],
            options={
                'db_table': 'datas',
            },
        ),
    ]
